# -*- coding: utf-8 -*-

from .context import preprocessing_dm

import json
import unittest
from pprint import pprint


class TestVituoso(unittest.TestCase):
    """Basic test cases."""
    @unittest.skip('')
    def test_get_all_data_sets_for_sparql(self):
        ref= []
        allDataSets = preprocessing_dm.get_all_names_of_named_graph('', '', use_cache=False)
        gnameLst = []
        for dname in allDataSets:
            lst = dname.split('-')
            if len(lst) > 1:
                dnameEnd = lst[-1]
                if dname.startswith('http://data.openbudgets.eu/resource/dataset') and 'codelist' not in dname \
                    and "1900" < dnameEnd < "3000":
                    gnameLst.append(dname)
        pprint(gnameLst)
        assert len(gnameLst) > 0
        assert False

    @unittest.skip('')
    def test_check_dataset_use_slice(self):
        allDimensions = []
        emptyDatasets = []
        allDimensionsRef = ['http://data.openbudgets.eu/ontology/dsd/ejecucionde-gastos2015/dimension/date',
 'http://purl.org/linked-data/cube#dimension',
 'http://data.openbudgets.eu/ontology/dsd/dimension/organization',
 'http://data.openbudgets.eu/ontology/dsd/ejecucionde-gastos2015/dimension/functional-classification',
 'http://data.openbudgets.eu/ontology/dsd/test3/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/fghfgh/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/test/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/begrotingsstatenv8/dimension/administrative-classification',
 'http://data.openbudgets.eu/ontology/dsd/begrotingsstatenv8/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/begrotingsstatenv8/dimension/direction',
 'http://data.openbudgets.eu/ontology/dsd/finnish_budget_2014/dimension/phase',
 'http://data.openbudgets.eu/ontology/dsd/dimension/fiscalPeriod',
 'http://data.openbudgets.eu/ontology/dsd/test1/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/france_cplf_2013_2014/dimension/phase',
 'http://data.openbudgets.eu/ontology/dsd/france_cplf_2013_2014/dimension/administrative-classification',
 'http://data.openbudgets.eu/ontology/dsd/france_cplf_2013_2014/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/france_cplf_2013_2014/dimension/functional-classification',
 'http://data.openbudgets.eu/ontology/dsd/france_cplf_2013_2014/dimension/expenditure-type',
 'http://data.openbudgets.eu/ontology/dsd/my-openspending-datapackage/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/dimension/fiscalYear',
 'http://data.openbudgets.eu/ontology/dsd/dimension/operationCharacter',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2007/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2007/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2007/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2007/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/testfdp5/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/greek-municipalities/dimension/budgetPhase',
 'http://data.openbudgets.eu/ontology/dsd/greek-municipalities/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-athens/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2004/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2005/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2006/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2007/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2008/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2009/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2004/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2005/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2006/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2007/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2008/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2009/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-athens-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/dimension/budgetPhase',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/greek-municipalities/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-heraklion-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-kalamaria/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2002/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-kalamaria-2002/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-kalamaria-2003/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2003/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-kalamaria-2004/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2004/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2005/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2006/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2007/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2008/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2009/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2002/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2003/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2004/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2005/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2006/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2007/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2008/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2009/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kalamaria-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/greek-municipalities-2016/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-karpenisi-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-katerini-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-naousa-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-rethymno-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-rethymno-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-sithonia-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/municipality-of-thessaloniki/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-thessaloniki-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-veroia-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2011/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/greek-regions/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus/dimension/Classification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2012/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2013/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2014/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2015/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-epirus-2016/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-epirus-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2011/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean/dimension/Classification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2012/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2013/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2014/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2015/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-expenditure-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/region-of-saegean-2016/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/budget-saegean-revenue-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/id/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/id/dimension/unknown',
 'http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/accountAssignmentElement',
 'http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/bonn-budget/dimension/operationCharacter',
 'http://data.openbudgets.eu/ontology/dimension/fiscalYear',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2006/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2006/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2006/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2006/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2008/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2008/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2008/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2008/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2009/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2009/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2009/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2009/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2010/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2010/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2010/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2010/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2011/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2011/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2011/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2011/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2012/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2012/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2012/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2012/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2013/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2013/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2013/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2013/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2014/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2014/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2014/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2014/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2015/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2015/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2015/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2015/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2016/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2016/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2016/dimension/functionalClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-exp-2016/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2006/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2006/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2006/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2007/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2007/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2007/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2008/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2008/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2008/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2009/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2009/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2009/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2010/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2010/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2010/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2011/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2011/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2011/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2012/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2012/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2012/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2013/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2013/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2013/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2016/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2016/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2016/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/fundingClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/administrativeClassification',
 'http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/economicClassification',
 'http://data.openbudgets.eu/ontology/dsd/subnat-expense-17/dimension/direction',
 'http://data.openbudgets.eu/ontology/dsd/subnat-expense-17/dimension/phase',
 'http://data.openbudgets.eu/ontology/dsd/subnat-expense-17/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/subnat-expense-17/dimension/fin-source',
 'http://data.openbudgets.eu/ontology/dsd/subnat-expense-17/dimension/administrative-classification',
 'http://data.openbudgets.eu/ontology/dsd/kutno_w2014-marek-pipeline-debug/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/kutno_w2014-marek-pipeline-debug/dimension/functional-classification',
 'http://data.openbudgets.eu/ontology/dsd/kutno_w2014-marek-pipeline-debug/dimension/economic-classification',
 'http://data.openbudgets.eu/ontology/dsd/id_coor_2016/dimension/budget-line-id',
 'http://data.openbudgets.eu/ontology/dsd/id_coor_2016/dimension/date',
 'http://data.openbudgets.eu/ontology/dsd/id_coor_2016/dimension/administrative-classification']


        emptyDatasetsRef = ['http://data.openbudgets.eu/aux',
 'http://data.openbudgets.eu/resource/graph/testfdp7',
 'http://data.openbudgets.eu/resource/graph/testfdp11',
 'http://data.openbudgets.eu/resource/graph/testfdp8',
 'http://data.openbudgets.eu/resource/graph/testfdp6',
 'http://data.openbudgets.eu/resource/graph/testfdp9']

        CodeList = ['http://data.openbudgets.eu/resource/codelist/budget-phase',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2011',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2012',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2013',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2015',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_i_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_i_aragon_2016',
 'http://data.openbudgets.eu/resource/codelist/kae-ota-exodwn-2014',
 'http://data.openbudgets.eu/resource/dataset/greek-municipalities/codelist/athens-administrations',
 'http://data.openbudgets.eu/resource/codelist/kae-ota-esodwn-2014',
 'http://data.openbudgets.eu/resource/codelist/kae-ota-administration-2014',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2006',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2007',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2008',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2009',
 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2010',
 'http://data.openbudgets.eu/resource/codelist/kae-ota',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2004/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2005/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2006/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2007/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2008/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2009/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2004/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2005/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2006/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2007/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2008/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2009/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-athens-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-heraklion-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2002/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2003/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2004/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2005/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2006/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2007/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2008/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2009/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2002/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2003/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2004/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2005/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2006/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2007/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2008/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2009/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kalamaria-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-karpenisi-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-katerini-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-naousa-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-rethymno-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-rethymno-revenues-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-sithonia-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-thessaloniki-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2010/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-veroia-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-epirus-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-expenditure-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2011/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2012/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2013/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2014/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2015/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-saegean-revenue-2016/codelist',
 'http://data.openbudgets.eu/resource/codelist/organization-identifier',
 'http://data.openbudgets.eu/resource/codelist/cl-geo',
 'http://data.openbudgets.eu/resource/codelist/cpa',
 'http://data.openbudgets.eu/resource/codelist/cpc',
 'http://data.openbudgets.eu/resource/codelist/currency',
 'http://data.openbudgets.eu/resource/codelist/esa2010-assets-and-liabilities',
 'http://data.openbudgets.eu/resource/codelist/esa2010-balancing-items-and-net-worth',
 'http://data.openbudgets.eu/resource/codelist/esa2010-distributive-transactions',
 'http://data.openbudgets.eu/resource/codelist/esa2010-financial-assets',
 'http://data.openbudgets.eu/resource/codelist/esa2010-institutional-sectors',
 'http://data.openbudgets.eu/resource/codelist/esa2010-non-financial-assets',
 'http://data.openbudgets.eu/resource/codelist/esa2010-other-changes-in-assets',
 'http://data.openbudgets.eu/resource/codelist/esa2010-transactions-in-products',
 'http://data.openbudgets.eu/resource/codelist/icatus',
 'http://data.openbudgets.eu/resource/codelist/isco_1988',
 'http://data.openbudgets.eu/resource/codelist/catpol',
 'http://data.openbudgets.eu/resource/codelist/oenace',
 'http://data.openbudgets.eu/resource/codelist/prodcom',
 'http://data.openbudgets.eu/resource/codelist/sitc',
 'http://data.openbudgets.eu/resource/codelist/sitc_austria',
 'http://data.openbudgets.eu/resource/codelist/stakod-greek',
 'http://data.openbudgets.eu/resource/dataset/budget-bonn-aemterhierarchie-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-bonn-kostenartengruppe-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-bonn-operationcharacter-2016/codelist',
 'http://data.openbudgets.eu/resource/dataset/budget-bonn-produktuebersicht-2016/codelist']


        allDataSets = preprocessing_dm.get_all_names_of_named_graph('', '', use_cache=False)
        for dname in allDataSets:
            result = preprocessing_dm.get_dimensions_from_dataset('<'+dname+'>')
            if not result and 'codelist' not in dname:
                emptyDatasets.append(dname)
            if not result and 'codelist' in dname:
                CodeList.append(dname)
            for d in result:
                if not d in allDimensions:
                    allDimensions.append(d)
        #print('empty datasets')
        #pprint(emptyDatasets)
        #print('totally ', len(allDimensions), ' dimensions')
        #print(len('emptyDatasets'), ' empty datasets')
        #pprint(CodeList)
        assert True


    @unittest.skip('')
    def test_get_all_observations_from_sliced_dataset(self):
        dataset1 = "<http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012>"
        reflst = [{'s': {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/slice/00.6031', 'type': 'uri'},
                   'functionalClassification':
                       {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/codelist/00/6031', 'type': 'uri'},
                   'budgetPhase': {'value': 'http://data.openbudgets.eu/resource/codelist/budget-phase/draft', 'type': 'uri'},
                   'administrativeClassification': {'value': 'http://data.openbudgets.eu/resource/codelist/kae-ota-administration-2014/00',
                                                    'type': 'uri'}, 'economicClassification':
                       {'value': 'http://data.openbudgets.eu/resource/codelist/kae-ota-exodwn-2014/6031', 'type': 'uri'},
                   'sfunc': {'value': 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2012/slice/slice-by-functionalCode',
                             'type': 'uri'},
                   'observation': {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/observation/00.6031/draft', 'type': 'uri'},
                   'amount': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'value': '123600', 'type': 'typed-literal'}},
                  {'s': {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/slice/00.6031', 'type': 'uri'},
                   'functionalClassification': {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/codelist/00/6031',
                                                'type': 'uri'},
                   'budgetPhase': {'value': 'http://data.openbudgets.eu/resource/codelist/budget-phase/executed', 'type': 'uri'},
                   'administrativeClassification': {'value': 'http://data.openbudgets.eu/resource/codelist/kae-ota-administration-2014/00', 'type': 'uri'},
                   'economicClassification': {'value': 'http://data.openbudgets.eu/resource/codelist/kae-ota-exodwn-2014/6031', 'type': 'uri'},
                   'sfunc': {'value': 'http://data.openbudgets.eu/ontology/dsd/budget-kilkis-expenditure-2012/slice/slice-by-functionalCode', 'type': 'uri'},
                   'observation': {'value': 'http://data.openbudgets.eu/resource/dataset/budget-kilkis-expenditure-2012/observation/00.6031/executed', 'type': 'uri'},
                   'amount': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'value': '123548.47', 'type': 'typed-literal'}}]
        item1 = reflst[0]
        item2 = reflst[1]
        result = preprocessing_dm.get_all_observations_from_sliced_dataset(dataset1)
        assert item1 in result
        assert item2 in result

    @unittest.skip('')
    def test_get_all_observations_from_nonsliced_dataset(self):
        dataset1 = "<http://data.openbudgets.eu/resource/dataset/aragon-expenditure-2010>"
        reflst = [
            {'observation': {
                'value': 'http://data.openbudgets.eu/resource/dataset/aragon-2010-expenditure/observation/10',
                'type': 'uri'}, 'amount': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'value': '610051.68',
                                           'type': 'typed-literal'}, 'economicClassification': {
                'value': 'http://data.openbudgets.eu/resource/codelist/estructura_economica_g_aragon_2010/121001',
                'type': 'uri'}, 'fundingClassification': {
                'value': 'http://data.openbudgets.eu/resource/codelist/estructura_financiacion_g_aragon_2010/91002',
                'type': 'uri'}, 'administrativeClassification': {
                'value': 'http://data.openbudgets.eu/resource/codelist/estructura_organica_aragon_2010/01010',
                'type': 'uri'}, 'functionalClassification': {
                'value': 'http://data.openbudgets.eu/resource/codelist/estructura_funcional_aragon_2010/1111',
                'type': 'uri'}}
        ]
        result = preprocessing_dm.get_all_observations_from_nonsliced_dataset(dataset1)
        print(result[0])
        assert reflst[0] in result



if __name__ == '__main__':
    unittest.main()